apiVersion: apps/v1
kind: Deployment
metadata:
  name: pass-deployment
  namespace: pass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pass
  template:
    metadata:
      labels:
        app: pass
    spec:
      containers:
        - name: pass
          image: dellabeneta/pass:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"